# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapreduce.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapreduce.proto\x12\tmapreduce\"-\n\nMapRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\x12\x11\n\tcentroids\x18\x02 \x03(\t\"s\n\x0bMapResponse\x12\x34\n\x07results\x18\x01 \x03(\x0b\x32#.mapreduce.MapResponse.ResultsEntry\x1a.\n\x0cResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\x12StartReduceRequest\x12\x0c\n\x04\x46lag\x18\x01 \x01(\x08\"!\n\x13StartReduceResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\",\n\rReduceRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\t\"2\n\x0eReduceResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x13\n\x0bnewCentroid\x18\x02 \x01(\t2\xd5\x01\n\x10MapReduceService\x12\x34\n\x03Map\x12\x15.mapreduce.MapRequest\x1a\x16.mapreduce.MapResponse\x12=\n\x06Reduce\x12\x18.mapreduce.ReduceRequest\x1a\x19.mapreduce.ReduceResponse\x12L\n\x0bStartReduce\x12\x1d.mapreduce.StartReduceRequest\x1a\x1e.mapreduce.StartReduceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapreduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPRESPONSE_RESULTSENTRY']._options = None
  _globals['_MAPRESPONSE_RESULTSENTRY']._serialized_options = b'8\001'
  _globals['_MAPREQUEST']._serialized_start=30
  _globals['_MAPREQUEST']._serialized_end=75
  _globals['_MAPRESPONSE']._serialized_start=77
  _globals['_MAPRESPONSE']._serialized_end=192
  _globals['_MAPRESPONSE_RESULTSENTRY']._serialized_start=146
  _globals['_MAPRESPONSE_RESULTSENTRY']._serialized_end=192
  _globals['_STARTREDUCEREQUEST']._serialized_start=194
  _globals['_STARTREDUCEREQUEST']._serialized_end=228
  _globals['_STARTREDUCERESPONSE']._serialized_start=230
  _globals['_STARTREDUCERESPONSE']._serialized_end=263
  _globals['_REDUCEREQUEST']._serialized_start=265
  _globals['_REDUCEREQUEST']._serialized_end=309
  _globals['_REDUCERESPONSE']._serialized_start=311
  _globals['_REDUCERESPONSE']._serialized_end=361
  _globals['_MAPREDUCESERVICE']._serialized_start=364
  _globals['_MAPREDUCESERVICE']._serialized_end=577
# @@protoc_insertion_point(module_scope)
