syntax = "proto3";

// python -m grpc_tools.protoc -I.\RPC  --python_out=. --pyi_out=.\ --grpc_python_out=. .\RPC\mapreduce.proto

package mapreduce;

service MapReduceService {
  rpc Map(MapRequest) returns (MapResponse);
  rpc Reduce(ReduceRequest) returns (ReduceResponse);
  rpc StartReduce(StartReduceRequest) returns (StartReduceResponse);
  rpc returnCentroid(returnReduce) returns (returnReduceResponse);
}

message MapRequest {
  int32 begin = 1;
  int32 end = 2;
  repeated point centroids = 3;
  int32 num_reducers = 4;
  bool append =5;
}

message MapResponse {
  string status = 1;
}

message StartReduceRequest{
  repeated int32 partitions = 1;
  int32 num_mappers = 2;
}

message StartReduceResponse{
  int32 ok=1;
}

message ReduceRequest {
  repeated int32 partitions = 1;
}

message returnReduce{
  int32 ok = 1;
}

message returnReduceResponse{
  int32 ok = 1;
}

message point{
  double x=1;
  double y=2;
}

message centroid_values{
  int32 key = 1;
  repeated point values = 2;
}

message ReduceResponse {
  repeated centroid_values dictionary = 1;
}

//TO ACCESS KEY: rr.centroid_values.key
//TO ACCESS VALUES: rr.dictionary.values[index].x/y