syntax = "proto3";

// python -m grpc_tools.protoc -I.\RPC  --python_out=. --pyi_out=.\ --grpc_python_out=. .\RPC\mapreduce.proto

package mapreduce;

service MapReduceService {
  rpc Map(MapRequest) returns (MapResponse);
  rpc Reduce(ReduceRequest) returns (ReduceResponse);
  rpc StartReduce(StartReduceRequest) returns (StartReduceResponse);
}

message point{
  float x=1;
  float y=2;
}

message MapRequest {
  int32 begin = 1;
  int32 end = 2;
  repeated point centroids = 3;
  int32 num_reducers = 4;
}

message MapResponse {
  string status = 1;
}

message StartReduceRequest{
  int32 Flag=1;
}

message StartReduceResponse{
  int32 ok=1;
}

message ReduceRequest {
  string key = 1;
  repeated string values = 2; 
}

message ReduceResponse {
  string key = 1;
  string newCentroid = 2;
}

